# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BubbleShowCaseSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BubbleShowCaseSample
  pod 'BubbleShowCase', '0.0.7-beta.2'

end
